### ISSUE TITLE
bot can't host more than 9 realms. 

### ISSUE THREAD

**Issue by cipriant** [OHSystem/OHSystem#372]
bot can't host more than 9 realms. 
even with :
for( uint32_t i = 1; i < 15; ++i )
is not host on all 15, mby is needed more modifications

**Comment by gladiko** [comment]
May be this can help https://www.ghostpp.com/forum/index.php?topic=381.msg2430#msg2430

**Comment by cipriant** [comment]
thank you for link, bot is underconstruction now...
