### ISSUE TITLE
The idea to optimize logs

### ISSUE THREAD

**Issue by Artyom91** [OHSystem/OHSystem#393]
If the log lobby and games are not stored in the database?
Can store them in files.

**Comment by Grief-Code** [comment]
Thats not an optimize.

But the plan is to do that already. However wont be available on that bot. Maybe on v2.

**Comment by Artyom91** [comment]
This optimization.

The database will not take 12 million unnecessary tables.

**Comment by Grief-Code** [comment]
BUt 24,000,000 files is better?

This is btw the live games table, you can pruge it.

**Comment by Artyom91** [comment]
I need a chat logs players)

**Comment by Grief-Code** [comment]
I dont get that. 
And i do not think i will modify the live games for that or implement a flooding like this.

**Comment by Artyom91** [comment]
I understood it all, perhaps it is not optimized.
