### ISSUE TITLE
Install boost

### ISSUE THREAD

**Issue by Potniy** [OHSystem/OHSystem#397]
The Installation Guide on Windows bot has a point installation Boost.
It is written:
• install boost
After you have opened the project we need to install boost libs:
     CTRL + R -> cmd -> Enter
     cd C: \ Libraries \ boost \
     bootstrap
     . \ b2
When I press on CTRL+R, he did not issue ... does not respond to this ...
Maybe you had in mind, click on the Windows+R?
Sorry for my english.

**Comment by Grief-Code** [comment]
Yea meant windows+r. Will fix it later, thanks for the info.
