### ISSUE TITLE
Error when compiling

### ISSUE THREAD

**Issue by Potniy** [OHSystem/OHSystem#398]
Compile projects ghost (ghost_v1) and he gave me a lot of mistakes.
What's wrong?

2>ohconnect.h(45): error C2146: syntax error : missing ';' before identifier 'N0'
2>ohconnect.h(45): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
2>ohconnect.h(45): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
2>ohconnect.h(46): error C2146: syntax error : missing ';' before identifier 'N'
2>ohconnect.h(46): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
2>ohconnect.h(46): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
2>ohconnect.h(47): error C2146: syntax error : missing ';' before identifier 'masking_key'
2>ohconnect.h(47): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
2>ohconnect.h(47): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
2>ohconnect.h(53): error C2143: syntax error : missing ';' before '*'
2>ohconnect.h(53): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
2>ohconnect.h(53): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
2>ohconnect.h(56): error C2146: syntax error : missing ';' before identifier 'm_Room'
2>ohconnect.h(56): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
2>ohconnect.h(56): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
2>ohconnect.h(57): error C2146: syntax error : missing ';' before identifier 'm_RoomName'
2>ohconnect.h(57): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
2>ohconnect.h(57): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
2>ohconnect.h(59): error C2146: syntax error : missing ';' before identifier 'IP'
2>ohconnect.h(59): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
2>ohconnect.h(59): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
2>ohconnect.h(60): error C2146: syntax error : missing ';' before identifier 'Port'
2>ohconnect.h(60): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
2>ohconnect.h(60): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
2>ohconnect.h(61): error C2143: syntax error : missing ';' before '<'
2>ohconnect.h(61): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
2>ohconnect.h(61): error C2238: unexpected token(s) preceding ';'
2>ohconnect.h(63): error C2146: syntax error : missing ';' before identifier 'm_LastSendTime'
2>ohconnect.h(63): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
2>ohconnect.h(63): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
2>ohconnect.h(65): error C2146: syntax error : missing ';' before identifier 'm_ClientID'
2>ohconnect.h(65): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
2>ohconnect.h(65): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
2>ohconnect.h(66): error C2039: 'vector' : is not a member of 'std'
2>ohconnect.h(66): error C2143: syntax error : missing ';' before '<'
2>ohconnect.h(66): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
2>ohconnect.h(66): error C2238: unexpected token(s) preceding ';'
2>ohconnect.h(67): error C2146: syntax error : missing ';' before identifier 'LastPingTime'
2>ohconnect.h(67): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
2>ohconnect.h(67): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
2>ohconnect.h(68): error C2146: syntax error : missing ';' before identifier 'LastConnectionAttemp'
2>ohconnect.h(68): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
2>ohconnect.h(68): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
2>ohconnect.h(73): error C2061: syntax error : identifier 'CGHost'
2>ohconnect.h(83): error C2061: syntax error : identifier 'string'
2>ohconnect.h(84): error C2061: syntax error : identifier 'string'
2>ohconnect.h(86): error C2146: syntax error : missing ';' before identifier 'wrapMessage'
2>ohconnect.h(86): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
2>ohconnect.h(86): error C2061: syntax error : identifier 'string'
2>ohconnect.h(86): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
2>ohconnect.h(86): warning C4183: 'wrapMessage': missing return type; assumed to be a member function returning 'int'
2>ohconnect.h(87): error C2061: syntax error : identifier 'string'
2>ohconnect.h(88): error C2027: use of undefined type 'CTCPClient'
2>          ohconnect.h(30) : see declaration of 'CTCPClient'
2>ohconnect.h(88): error C2227: left of '->GetConnected' must point to class/struct/union/generic type

**Comment by Potniy** [comment]
Grief-Code, tell me, please, how to resolve this problem?

**Comment by Grief-Code** [comment]
Dont use windows :smiley: 

Checkout the following branch and try to compile it:
https://github.com/OHSystem/OHSystem/tree/remove_ohconnect_depency

**Comment by Grief-Code** [comment]
I have merged this branch into the master branch now,

I will reqrite that probably into a modular system.
