### ISSUE TITLE
Add a small anti-cheat

### ISSUE THREAD

**Issue by Artyom91** [OHSystem/OHSystem#401]
![2015-02-26_184204](https://cloud.githubusercontent.com/assets/6318282/6388585/3dd899f6-bde7-11e4-84cd-ce84a23fe461.png)
![2015-02-26_184227](https://cloud.githubusercontent.com/assets/6318282/6388586/3dd96c00-bde7-11e4-9e14-71426768cd01.png)

Please add the ban on writing commands:
 -lvlup
-gold

**Comment by Grief-Code** [comment]
Uhm.

Why this should be a ban? This is actually not working...

**Comment by anonprophet** [comment]
no need, this command only working in -test mode
u must disallow -test in !hcl command

**Comment by Artyom91** [comment]
what? 

Game: https://hodovoi.ru/warcraft3/?game=169988
00:00Bot apso

**Comment by Artyom91** [comment]
Maybe it's a new cheat. I propose to introduce a ban on entering these commands. How to implement?

**Comment by Grief-Code** [comment]
Can you upload a replay?

**Comment by Artyom91** [comment]
The game was a draw...

https://hodovoi.ru/warcraft3/?game=170024

Russian LNG download replay: :)

![2015-02-27_013730](https://cloud.githubusercontent.com/assets/6318282/6395009/4549e778-be21-11e4-9d54-6008b194beb4.png)

**Comment by Grief-Code** [comment]
Its test mode....

**Comment by Artyom91** [comment]
I do not understand. I have a level 25 players play, what to do?

**Comment by anonprophet** [comment]
its a -test game mode
-test = enable single player commands

Single Player Commands
```
lvlup #	Increases level of your hero by entered value.
refresh	Resets ability cooldowns, sets health and mana of your hero to 100%.
spawncreeps	Spawns creeps from all lanes.
powerup	Spawns runes.
neutrals	Forces neutral spawn.
kill	Kills your last picked hero. This kill will be considered as a suicide.
gold #	Increases your gold by entered value.
time #	Sets time of day. Values should be between 0 and 24.
killsent	Kills sentinel creeps.
killscourge	Kills scourge creeps.
killall	Kills all creeps.
noherolimitt	Allows you to pick multiple heroes.
trees	Forces a tree spawn.
killwards	Removes wards from the map.
spawnon	Enables creep spawn. This is enabled initially.
spawnoff	Disables creep spawn.
```

**Comment by Artyom91** [comment]
So anyone can put themselves level 25 with 1 minute?

**Comment by Grief-Code** [comment]
With using -test at gamestart, yes.

**Comment by Artyom91** [comment]
What the -test?

**Comment by cipriant** [comment]
hodovoi.ru, where is the ohsysyem copyright?

**Comment by Artyom91** [comment]
Look carefully.

**Comment by Grief-Code** [comment]
He is correct, you really removed it.

As I expected it probably, but this was 5 month back.

**Comment by Artyom91** [comment]
![2015-02-28_005935](https://cloud.githubusercontent.com/assets/6318282/6414700/1d446a5e-bee5-11e4-9a11-ecac7972eb75.png)

**Comment by Artyom91** [comment]
Will you help me?

**Comment by Artyom91** [comment]
@Grief-Code Will you help me?

**Comment by Grief-Code** [comment]
I will maybe add a patch soon, but im not sure, since this is actually not a common problem.

**Comment by Artyom91** [comment]
@Grief-Code Yes, but once introduced.
