### ISSUE TITLE
Game Version Failed

### ISSUE THREAD

**Issue by interkill** [OHSystem/OHSystem#403]
I get this error when I checked
[Tue Mar  3 20:51:36 2015] [GHOST] starting up
[Tue Mar  3 20:51:36 2015] [GHOST] using log method 1, logging is enabled and [ghost.log] will not be locked
[Tue Mar  3 20:51:36 2015] [GHOST] using monotonic timer with resolution 0.00 microseconds
[Tue Mar  3 20:51:36 2015] [PLUGIN] 
[Tue Mar  3 20:51:36 2015] [PLUGIN] ***************************************************************************************
[Tue Mar  3 20:51:36 2015] [PLUGIN] **                          INITIALIZE PYTHON PLUGIN MODULE                          **
[Tue Mar  3 20:51:36 2015] [PLUGIN] ***************************************************************************************
[Tue Mar  3 20:51:36 2015] [PLUGIN] 
[Tue Mar  3 20:51:36 2015] [GHOST] opening primary database
[Tue Mar  3 20:51:36 2015] [MYSQL] connecting to database server
[Tue Mar  3 20:51:36 2015] [GHOST] attempting to find local IP addresses
[Tue Mar  3 20:51:36 2015] [GHOST] local hostname is [sxleon58-VirtualBox]
[Tue Mar  3 20:51:36 2015] [GHOST] local IP address #1 is [127.0.1.1]
[Tue Mar  3 20:51:36 2015] [GHOST] acting as Warcraft III: Reign of Chaos
[Tue Mar  3 20:51:36 2015] [GHOST] loading file [ranks.txt]
[Tue Mar  3 20:51:36 2015] [GHOST] loading file [rooms.txt]
[Tue Mar  3 20:51:36 2015] [GHOST] found battle.net connection #1 for server [bnet.weplaes.com]
[Tue Mar  3 20:51:36 2015] [GHOST] unable to get system locale, using default locale of 1033
[Tue Mar  3 20:51:36 2015] [BNET: USWest] pvpgn connection found with a configured BNLS server, ignoring BNLS server
[Tue Mar  3 20:51:36 2015] [GHOST] Adding hardcoded Garena Realm & WC3Connect Realm.
[Tue Mar  3 20:51:36 2015] [GHOST] loading MPQ file [Warcraft/War3Patch.mpq]
[Tue Mar  3 20:51:36 2015] [GHOST] extracting Scripts\common.j from MPQ file to [mapcfgs/common.j]
[Tue Mar  3 20:51:36 2015] [GHOST] extracting Scripts\blizzard.j from MPQ file to [mapcfgs/blizzard.j]
[Tue Mar  3 20:51:36 2015] [GHOST] adding ".cfg" to default map -> new default is [wormwar.cfg]
[Tue Mar  3 20:51:36 2015] Unrecognized AliasType, make sure you have set it correctly.
[Tue Mar  3 20:51:36 2015] [GHOST] GHost++ Version 17.2 (with MySQL support)
[Tue Mar  3 20:51:36 2015] [GHOST] error listening for GProxy++ reconnects on port 6114
[Tue Mar  3 20:51:36 2015] [BNET: USWest] refreshed ban list (0 -> 0 bans)
[Tue Mar  3 20:51:36 2015] [BNET: USWest] connecting to server [bnet.weplaes.com] on port 6112
[Tue Mar  3 20:51:36 2015] [BNET: USWest] resolved and cached server IP address 144.76.197.52
[Tue Mar  3 20:51:36 2015] [BNET: Garena] refreshed ban list (0 -> 0 bans)
[Tue Mar  3 20:51:36 2015] [BNET: WC3Connect] refreshed ban list (0 -> 0 bans)
[Tue Mar  3 20:51:36 2015] [BNET: USWest] connected
[Tue Mar  3 20:51:36 2015] [BNET: USWest] attempting to auth as Warcraft III: The Frozen Throne
[Tue Mar  3 20:51:37 2015] [BNET: USWest] logon failed - game version is invalid, disconnecting
[Tue Mar  3 20:51:37 2015] [BNET: USWest] disconnected from battle.net
[Tue Mar  3 20:51:37 2015] [BNET: USWest] waiting 90 seconds to reconnect

**Comment by Grief-Code** [comment]
The question can be found also here:
https://www.ghostpp.com/forum/index.php?topic=438.0

And i think it got answered.

Regards
