### ISSUE TITLE
PVPGN Dysfunctional

### ISSUE THREAD

**Issue by interkill** [OHSystem/OHSystem#404]
#####################
# PVPGN INTEGRATION #
#####################

## enable pvpgn mode here, bot will not listen on user commands only on pvpgn commands
oh_pvpgn_mode = 1

[Wed Mar 04 20:13:01 2015] [WHISPER: USEast] ...] /pvpgn host ... 5x5 ar ONLY PROS!
[Wed Mar 04 20:13:54 2015] [OHSystem-Performance-Check] AVGTicks: 49ms | MaxTicks: 280ms | MinTicks: 0ms | Updates: 1197
[Wed Mar 04 20:14:54 2015] [OHSystem-Performance-Check] AVGTicks: 50ms | MaxTicks: 140ms | MinTicks: 0ms | Updates: 1200

Does not react?

**Comment by Grief-Code** [comment]
Because this patch was added and never finished. Since it seems that the pvpgn creator isnt that interested into it.

**Comment by HarpyWar** [comment]
@Grief-Code hey, mate! There is a task with PvPGN integration still unfinished on OHSystem side https://github.com/OHSystem/OHSystem/issues/279
Probably there some misunderstanding was occured between us. 
Can we reactivate our "partnership"?

Btw, now it is possible to create auto matchmaking with dota map http://forums.harpywar.com/viewtopic.php?pid=7093#p7093 using ExtraWork feature. It will be really great if we can do it with a hostbot.

**Comment by Grief-Code** [comment]
@HarpyWar Hey,
it was actually not this issue, it was probably an issue of lacking time in my way.
I want to start with a new bot tomorrow or today which is probably a light version and where i can consider integrating that once again.

But same as here, i do not know how its working from the time. I will try my best, but if i note that this is going to be too time consuming i probably need to stop on that.

**Comment by HarpyWar** [comment]
Okay, I see. I will write a short step-by-step tutorial on the week how you should test the current functionality that is implemented in PvPGN (I also forgot how exactly it should work). 

Earlier you gave me access for a vds, but there was no rights to run a pvpgn or a bot. Actually you should not install and configure PvPGN, I've already run a fresh installation on `server.pvpgn.pro` and you can test your bot directly on this server.

What about auto matchmaking I still don't know defails about how it works and it should be investigated deeper with a lot of testing. But if we reach this step I'll provide an additional information about implementation on a bot side.

**Comment by HarpyWar** [comment]
@Grief-Code I've posted details in the related topic a week ago.
Do you have any news, problems, may be questions? :)

**Comment by Grief-Code** [comment]
I read them and noted them. But i dont have time to work on it, for now.
Im really busy with a lot personal stuff etc, so it probably will take a bit time
