### ISSUE TITLE
?

### ISSUE THREAD

**Issue by Artyom91** [OHSystem/OHSystem#408]
./ghost++
***************************************************************************************
**                      WELCOME TO THE OHSYSTEM BOT V2                               **
**       PLEASE DO NOT REMOVE ANY COPYRIGHT NOTICE TO RESPECT THE PROJECT            **
**       ----------------------------------------------------------------            **
**        For any questions and required support use our git repository              **
**                    https://github.com/OHSystem/OHSystem                           **
***************************************************************************************

***************************************************************************************
**                             INITIALIZE GHOST MODULE                               **
***************************************************************************************

[GHOST] starting up
[GHOST] using log method 1, logging is enabled and [ghost.log] will not be locked
[GHOST] using monotonic timer with resolution 0.00 microseconds
[PLUGIN] Traceback (most recent call last):
[PLUGIN]   File "./plugins/__init__.py", line 1, in <module>
[PLUGIN]     import test_module
[PLUGIN] ImportError: No module named test_module
terminate called after throwing an instance of 'boost::python::error_already_set'
Аварийный останов

**Comment by Grief-Code** [comment]
Fixed 7679328bd194fb7ba26f975950716b80e8dc9c4a
