### ISSUE TITLE
?

### ISSUE THREAD

**Issue by Artyom91** [OHSystem/OHSystem#409]
[GHOST] acting as Warcraft III: Reign of Chaos

bot_tft = 1

**Comment by Artyom91** [comment]
@Grief-Code Help please :)

**Comment by Grief-Code** [comment]
I'm wondering if this is a comon issue.
I'm also connected through TFT and got this setting, please lookup your config, if you don't override it somewhere later.

**Comment by Artyom91** [comment]
@Grief-Code 

![2015-03-24_200811](https://cloud.githubusercontent.com/assets/6318282/6799434/851d4652-d261-11e4-9fcd-c880e0443380.png)

Config: https://hodovoi.ru/default.cfg

**Comment by Grief-Code** [comment]
Yea we have the same issue, im looking it up.
