### ISSUE TITLE
Error segmentation

### ISSUE THREAD

**Issue by Artyom91** [OHSystem/OHSystem#410]
After correcting - https://github.com/OHSystem/OHSystem/commit/8998a48e845c3cdf808cfec632c0a6297bd7ea7f Error segmentation

![2015-03-24_204602](https://cloud.githubusercontent.com/assets/6318282/6800038/cef30348-d266-11e4-96fd-a39cd9589bd3.png)

MAKE:

![2015-03-24_204707](https://cloud.githubusercontent.com/assets/6318282/6800060/f42e1d3c-d266-11e4-973b-d71518e04140.png)

**Comment by Grief-Code** [comment]
Use gdb to determine the reason please

**Comment by Artyom91** [comment]
![2015-03-24_210119](https://cloud.githubusercontent.com/assets/6318282/6800313/eeab2a7e-d268-11e4-83d8-babb35e41d63.png)

**Comment by Artyom91** [comment]
@Grief-Code Sorry, you're working hard to eliminate?

**Comment by Grief-Code** [comment]
naahhhhh :smile: 

Just revert the previous commit and ignore the issue with the bnet connections :-)

**Comment by Artyom91** [comment]
@Grief-Code What???

**Comment by Artyom91** [comment]
@Grief-Code Without this fix, I load map and throws, but card I have https://github.com/OHSystem/OHSystem/commit/8998a48e845c3cdf808cfec632c0a6297bd7ea7f .

**Comment by Artyom91** [comment]
@Grief-Code fixed:

![2015-03-26_062342](https://cloud.githubusercontent.com/assets/6318282/6834575/af3ea032-d380-11e4-8dbb-935eb92b7cd4.png)
