### ISSUE TITLE
[GAMEPROTO] invalid parameters passed to SEND_W3GS_CHAT_FROM_HOST

### ISSUE THREAD

**Issue by Artyom91** [OHSystem/OHSystem#411]
What is it?

**Comment by Grief-Code** [comment]
show me log where that happen. 
I guess its `!vr`

**Comment by cipriant** [comment]
i knew it, u always had a private repo, the good version ! this test repo help you to fix bugs, to get new ideeas :smile:

**Comment by Grief-Code** [comment]
The private repository is present since ~ 4 weeks, since we got a copy paste master which started to annoy me.
Hit me when you want access to it.

**Comment by Artyom91** [comment]
@Grief-Code Tell me, I have little published information about bugs or additions? Participated in the Russification, I'm a bad party?

**Comment by Grief-Code** [comment]
I never said that, but its against someone else and i found some more sites acting similair.

You might wanna look up this site:
https://ghostplay.de/

Which is literally getting all our ideas implemented, but probably in the worst way of programming. And he cannot programm C++, so this is the reason why i closed my work literally here. I have made  a plugin system, where im implementing new patches and ideas, where i dont need to touch the bot code anymore.

Tell me @Artyom91 are you using the latest bot version from this repository?
We are current experiencing main issues with the database, and im investigate a lot of time into fixing it, so it would be interesting for you to also have access to the repository.

Just shoot me a mail at admin@gcoding.net with your mail and i will add you to our gitlab system.

**Comment by Artyom91** [comment]
@Grief-Code I use an old, on a new project there are no statistics, but I need it. Now send a letter.

**Comment by cipriant** [comment]
"Hit me when you want access to it."
ty grief, i will sent a email in few hours.

**Comment by Artyom91** [comment]
?

**Comment by Artyom91** [comment]
@Grief-Code when give access?

**Comment by Grief-Code** [comment]
soon.

We issued the last time some small problems and also our mailserver doesnt work as expected. Without the mail you wouldnt be able to complete a registration step.
