### ISSUE TITLE
error while loading shared libraries: libboost_date_time.so.1.55.0:

### ISSUE THREAD

**Issue by Artyom91** [OHSystem/OHSystem#414]
Help me setup libboost_date_time.so.1.55.0
I am use debian 7.8 (Wheezy)

**Comment by Grief-Code** [comment]
debian is fine, but takes a lot of time with security fixes and patching.
I recommend using ubuntu 1404 lts.

On debian you manually need to install boost.

download it, untar it, run `./bjam` and `./bjam install`

On ubunutu you have that packet included in the distru, also if its 1.49, but that shouldnt matter :-)

**Comment by Artyom91** [comment]
Fixed.

./ghost++2: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by ./ghost++2)
