### ISSUE TITLE
[1045] Access denied

### ISSUE THREAD

**Issue by Potniy** [OHSystem/OHSystem#415]
When I install Openstats on Ubuntu 14.04 I'm having problems.
During the installation OpenStats fields are filled as follows:
Server - localhost
DB username - root
DB password - ********
Datebase - Ohsystem

Test connections... Successfully connected to database... Continue... Data successfully updated... Continue... Creating tables...
Error!: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: NO)

Why are issues that the password is incorrect, because he has successfully connected to the database. Please help.

**Comment by Potniy** [comment]
This problem is solved, there appeared another. 
After installing OpenStats throws on http://localhost/ohsystem/openstats and such a section I have not. Please help.

**Comment by Potniy** [comment]
Problem solved, there appeared another.
When you go to the Admin panel it gives me this error:
Fatal error: Cannot redeclare readLine() in /var/www/html/adm/admin_func.php on line 42
Please help.

**Comment by Grief-Code** [comment]
Open the following files:
__openstats/adm/admin_func.php__ and find: `function readLine` and replace to `function readLineStr`
__adm/admin_plugins.php__ and find `readLine` and replace to `readLineStr`

This issue is that the new php5 version added a readline function which is now in conflict with the selfwritten function.

**Comment by Potniy** [comment]
Thanks for help, and how to be?
Warning: file_put_contents(../config.php): failed to open stream: Permission denied in /var/www/html/inc/common.php on line 726

This warning comes when save changes to the Configuration in the Admin panel. And not only with configurations, but with the plugins.

**Comment by Grief-Code** [comment]
Share me a link to your webspace.
