### ISSUE TITLE
/usr/bin/ld: cannot find -lboost_python

### ISSUE THREAD

**Issue by Artyom91** [OHSystem/OHSystem#416]
-lboost_filesystem -lpython2.7 -lboost_python -lrt
/usr/bin/ld: cannot find -lboost_python
collect2: error: ld returned 1 exit status
make: *** [ghost++] Ошибка 1
-------------------------------------------------------------------

# sudo apt-get install libboost-python-dev
Чтение списков пакетов… Готово
Построение дерева зависимостей
Чтение информации о состоянии… Готово
Будут установлены следующие дополнительные пакеты:
  gccxml libboost-python1.49-dev libboost1.49-dev libicu48
Предлагаемые пакеты:
  libboost1.49-doc libboost-chrono1.49-dev libboost-date-time1.49-dev libboost-filesystem1.49-dev libboost-graph-parallel1.49-dev libboost-graph1.49-dev
  libboost-iostreams1.49-dev libboost-locale1.49-dev libboost-math1.49-dev libboost-mpi1.49-dev libboost-program-options1.49-dev libboost-random1.49-dev
  libboost-regex1.49-dev libboost-serialization1.49-dev libboost-signals1.49-dev libboost-system1.49-dev libboost-test1.49-dev libboost-thread1.49-dev
  libboost-timer1.49-dev libboost-wave1.49-dev xsltproc doxygen docbook-xml docbook-xsl default-jdk fop

**Comment by Grief-Code** [comment]
`lboost_python` is a part of the boostfiles, you should install boost 1.55 then it should work.

**Comment by Artyom91** [comment]
fixed )

**Comment by Grief-Code** [comment]
How did you fix it, just so we know if someone experience the same issue in the future.

Im probably unable atm to give you access to the hidden repository because we issue still problems with our mailserver connection. Im investigating to fix that.

**Comment by Artyom91** [comment]
I am delete libboost-all-dev (debian version only 1.49).

Installing from Source:
wget http://downloads.sourceforge.net/project/boost/boost/1.57.0/boost_1_57_0.zip
