### ISSUE TITLE
does ohsystem have anti MH ?

### ISSUE THREAD

**Issue by anonprophet** [OHSystem/OHSystem#419]
does ohsystem have anti MH ? (tyranO)

i see this banner

http://stats.ohsystem.net/themes/global/img/banners/ohs_ac.jpg

**Comment by Grief-Code** [comment]
Ohsystem yes, we host maphack free games thanks to some interaction with the mapmakers.

**Comment by Artyom91** [comment]
@Grief-Code You can show the user manual? We also have mapmakers.

**Comment by Grief-Code** [comment]
Im sorry but this code is not shareable. We investigated a lot of time and work into this and created that.

**Comment by anonprophet** [comment]
its work on Maphack in DotA official grief ?

**Comment by Grief-Code** [comment]
No ;-) We made it mainly for lod, but it works also on the unofficial dota mirror which we might host soon,

**Comment by anonprophet** [comment]
unofficial map dracolich u mean?

**Comment by Artyom91** [comment]
If you give the source map, you do?

**Comment by Grief-Code** [comment]
Exactly, no i(we) dont share sources.

**Comment by anonprophet** [comment]
grief, http://d1stats.ru/ are u dracolich ?
© Grief-Code - Unofficial DotA Download Mirror

u will support this map for AMH ?

**Comment by Grief-Code** [comment]
Im not dracolich, i just supported him creating the mirror. Its probably only a 10 min work :D

**Comment by cipriant** [comment]
is 10 min work, i added too in imba map ;)

**Comment by anonprophet** [comment]
btw, this make MH tools doesnt work or just tell if someone use MH ?

**Comment by cipriant** [comment]
just tell when some1 use mh
