### ISSUE TITLE
Help compiled GCB

### ISSUE THREAD

**Issue by Artyom91** [OHSystem/OHSystem#420]
Help compiled GCB.

I run command:
javac -classpath .:../bin/lib/* gcb/Main.java
java -classpath .:../bin/lib/* gcb.Main

All is well, GCB works. How now do it in gcb.jar?

**Comment by Grief-Code** [comment]
I cannot help you there, since im not that familair with java.

**Comment by Artyom91** [comment]
@Grief-Code Even compiled do not know how?

**Comment by Grief-Code** [comment]
no.
