### ISSUE TITLE
'ohconnect.cpp': No such file or directory

### ISSUE THREAD

**Issue by Cedyk** [OHSystem/OHSystem#422]
This file ''ohconnect.cpp" not exist..can you helpme?

1>------ Operación Generar iniciada: proyecto: ghost, configuración: Debug Win32 ------
1>  ohconnect.cpp
1>c1xx : fatal error C1083: No se puede abrir el archivo código fuente: 'ohconnect.cpp': No such file or directory
1>  ghostdbmysql.cpp
1>c:\users\rodrigo\desktop\ghost\src\ghostdbmysql.cpp(1446): warning C4244: '=' : conversión de 'my_ulonglong' a 'uint32_t'; posible pérdida de datos
1>c:\users\rodrigo\desktop\ghost\src\ghostdbmysql.cpp(1473): warning C4244: '=' : conversión de 'my_ulonglong' a 'uint32_t'; posible pérdida de datos
1>c:\users\rodrigo\desktop\ghost\src\ghostdbmysql.cpp(1490): warning C4244: '=' : conversión de 'my_ulonglong' a 'uint32_t'; posible pérdida de datos
1>c:\users\rodrigo\desktop\ghost\src\ghostdbmysql.cpp(1496): warning C4244: '=' : conversión de 'my_ulonglong' a 'uint32_t'; posible pérdida de datos
1>c:\users\rodrigo\desktop\ghost\src\ghostdbmysql.cpp(1502): warning C4244: '=' : conversión de 'my_ulonglong' a 'uint32_t'; posible pérdida de datos
1>c:\users\rodrigo\desktop\ghost\src\ghostdbmysql.cpp(2062): warning C4244: '=' : conversión de 'my_ulonglong' a 'uint32_t'; posible pérdida de datos
1>c:\users\rodrigo\desktop\ghost\src\ghostdbmysql.cpp(2104): warning C4244: '=' : conversión de 'my_ulonglong' a 'uint32_t'; posible pérdida de datos
1>c:\users\rodrigo\desktop\ghost\src\ghostdbmysql.cpp(2225): warning C4244: '=' : conversión de 'my_ulonglong' a 'uint32_t'; posible pérdida de datos
1>c:\users\rodrigo\desktop\ghost\src\ghostdbmysql.cpp(2512): warning C4244: '=' : conversión de 'my_ulonglong' a 'uint32_t'; posible pérdida de datos
1>c:\users\rodrigo\desktop\ghost\src\ghostdbmysql.cpp(2517): warning C4244: '=' : conversión de 'my_ulonglong' a 'uint32_t'; posible pérdida de datos
1>c:\users\rodrigo\desktop\ghost\src\ghostdbmysql.cpp(2544): warning C4244: '=' : conversión de 'my_ulonglong' a 'uint32_t'; posible pérdida de datos
1>c:\users\rodrigo\desktop\ghost\src\ghostdbmysql.cpp(2745): warning C4244: '=' : conversión de 'my_ulonglong' a 'uint32_t'; posible pérdida de datos
1>  Generando código...
========== Generar: 0 correctos, 1 incorrectos, 0 actualizados, 0 omitidos ==========

**Comment by Grief-Code** [comment]
I stopped support for windows, please report only issues regarding UNIX distributations.
