### ISSUE TITLE
Tried to compile ther src file got a lot of errors..

### ISSUE THREAD

**Issue by Aviator-Coding** [OHSystem/OHSystem#423]
uname -a:
Linux OhSystem 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt9-3~deb8u1 (2015-04-24) x86_64 GNU/Linux

                 from includes.h:44,
                 from ghost.h:26,
                 from bnet.cpp:23:
/usr/include/boost/ref.hpp:64:63: note: in passing argument 1 of `const boost::r
eference_wrapper<T> boost::ref(T&) [with T = CBNET*]'
 template<class T> inline reference_wrapper<T> BOOST_REF_CONST ref(T & t)
                                                               ^
In file included from ghost.h:26:0,
                 from bnet.cpp:23:
bnet.cpp:1072:59: error: invalid initialization of non-const reference of type `
CBNET*&' from an rvalue of type `CBNET*'
      EXECUTE_HANDLER("BNetTimeout", false, boost::ref(this))
                                                           ^
includes.h:88:53: note: in definition of macro `EXECUTE_HANDLER'
      bool Val = boost::python::extract<bool>( (*i)( __VA_ARGS__ ) );        \
                                                     ^
In file included from /usr/include/boost/thread/detail/thread.hpp:27:0,
                 from /usr/include/boost/thread/thread_only.hpp:22,
                 from /usr/include/boost/thread/thread.hpp:12,
                 from /usr/include/boost/thread.hpp:13,
                 from includes.h:44,
                 from ghost.h:26,
                 from bnet.cpp:23:
/usr/include/boost/ref.hpp:64:63: note: in passing argument 1 of `const boost::r
eference_wrapper<T> boost::ref(T&) [with T = CBNET*]'
 template<class T> inline reference_wrapper<T> BOOST_REF_CONST ref(T & t)
                                                               ^
In file included from ghost.h:26:0,
                 from bnet.cpp:23:
bnet.cpp: In member function `void CBNET::ProcessPackets()':
bnet.cpp:1372:62: error: invalid initialization of non-const reference of type `
CBNET*&' from an rvalue of type `CBNET*'
           EXECUTE_HANDLER("BNetLogged", true, boost::ref(this))
                                                              ^
includes.h:88:53: note: in definition of macro `EXECUTE_HANDLER'
      bool Val = boost::python::extract<bool>( (*i)( __VA_ARGS__ ) );        \
                                                     ^
In file included from /usr/include/boost/thread/detail/thread.hpp:27:0,
                 from /usr/include/boost/thread/thread_only.hpp:22,
                 from /usr/include/boost/thread/thread.hpp:12,
                 from /usr/include/boost/thread.hpp:13,
                 from includes.h:44,
                 from ghost.h:26,
                 from bnet.cpp:23:
/usr/include/boost/ref.hpp:64:63: note: in passing argument 1 of `const boost::r
eference_wrapper<T> boost::ref(T&) [with T = CBNET*]'
 template<class T> inline reference_wrapper<T> BOOST_REF_CONST ref(T & t)
                                                               ^
In file included from ghost.h:26:0,
                 from bnet.cpp:23:
bnet.cpp:1374:59: error: invalid initialization of non-const reference of type `
CBNET*&' from an rvalue of type `CBNET*'
       EXECUTE_HANDLER("BNetLogged", false, boost::ref(this))
                                                           ^
includes.h:88:53: note: in definition of macro `EXECUTE_HANDLER'
      bool Val = boost::python::extract<bool>( (*i)( __VA_ARGS__ ) );        \
                                                     ^
In file included from /usr/include/boost/thread/detail/thread.hpp:27:0,
                 from /usr/include/boost/thread/thread_only.hpp:22,
                 from /usr/include/boost/thread/thread.hpp:12,
                 from /usr/include/boost/thread.hpp:13,
                 from includes.h:44,
                 from ghost.h:26,
                 from bnet.cpp:23:
/usr/include/boost/ref.hpp:64:63: note: in passing argument 1 of `const boost::r
eference_wrapper<T> boost::ref(T&) [with T = CBNET*]'
 template<class T> inline reference_wrapper<T> BOOST_REF_CONST ref(T & t)
                                                               ^
In file included from ghost.h:26:0,
                 from bnet.cpp:23:
bnet.cpp: In member function `void CBNET::BotCommand(std::string, std::string, b
ool, bool)':
bnet.cpp:1604:61: error: invalid initialization of non-const reference of type `
CBNET*&' from an rvalue of type `CBNET*'
         EXECUTE_HANDLER("BNetCommand", true, boost::ref(this), User, Command, P
ayload)
                                                             ^
includes.h:88:53: note: in definition of macro `EXECUTE_HANDLER'
      bool Val = boost::python::extract<bool>( (*i)( __VA_ARGS__ ) );        \
                                                     ^
In file included from /usr/include/boost/thread/detail/thread.hpp:27:0,
                 from /usr/include/boost/thread/thread_only.hpp:22,
                 from /usr/include/boost/thread/thread.hpp:12,
                 from /usr/include/boost/thread.hpp:13,
                 from includes.h:44,
                 from ghost.h:26,
                 from bnet.cpp:23:
/usr/include/boost/ref.hpp:64:63: note: in passing argument 1 of `const boost::r
eference_wrapper<T> boost::ref(T&) [with T = CBNET*]'
 template<class T> inline reference_wrapper<T> BOOST_REF_CONST ref(T & t)
                                                               ^
In file included from ghost.h:26:0,
                 from bnet.cpp:23:
bnet.cpp:1606:58: error: invalid initialization of non-const reference of type `
CBNET*&' from an rvalue of type `CBNET*'
     EXECUTE_HANDLER("BNetCommand", false, boost::ref(this), User, Command, Payl
oad)
                                                          ^
includes.h:88:53: note: in definition of macro `EXECUTE_HANDLER'
      bool Val = boost::python::extract<bool>( (*i)( __VA_ARGS__ ) );        \
                                                     ^
In file included from /usr/include/boost/thread/detail/thread.hpp:27:0,
                 from /usr/include/boost/thread/thread_only.hpp:22,
                 from /usr/include/boost/thread/thread.hpp:12,
                 from /usr/include/boost/thread.hpp:13,
                 from includes.h:44,
                 from ghost.h:26,
                 from bnet.cpp:23:
/usr/include/boost/ref.hpp:64:63: note: in passing argument 1 of `const boost::r
eference_wrapper<T> boost::ref(T&) [with T = CBNET*]'
 template<class T> inline reference_wrapper<T> BOOST_REF_CONST ref(T & t)
                                                               ^
make: *** [bnet.o] Error 1
root@OhSystem:/home/wc3_hostbot/Bot/OHSystem-master/ghost/src# nano make.txt
root@OhSystem:/home/wc3_hostbot/Bot/OHSystem-master/ghost/src# make
g++ -o bnet.o  -O3 -g -DGHOST_MYSQL -I. -I./bncsutil/src/ -I./StormLib/ -I /usr/
include/python2.7/ -c bnet.cpp
In file included from ghost.h:26:0,
                 from bnet.cpp:23:
bnet.cpp: In member function `bool CBNET::Update(void*, void*)':
bnet.cpp:919:63: error: invalid initialization of non-const reference of type `C
BNET*&' from an rvalue of type `CBNET*'
          EXECUTE_HANDLER("BNetIPBanned", true, boost::ref(this))
                                                               ^
includes.h:88:53: note: in definition of macro `EXECUTE_HANDLER'
      bool Val = boost::python::extract<bool>( (*i)( __VA_ARGS__ ) );        \
                                                     ^
In file included from /usr/include/boost/thread/detail/thread.hpp:27:0,
                 from /usr/include/boost/thread/thread_only.hpp:22,
                 from /usr/include/boost/thread/thread.hpp:12,
                 from /usr/include/boost/thread.hpp:13,
                 from includes.h:44,
                 from ghost.h:26,
                 from bnet.cpp:23:
/usr/include/boost/ref.hpp:64:63: note: in passing argument 1 of `const boost::r
eference_wrapper<T> boost::ref(T&) [with T = CBNET*]'
 template<class T> inline reference_wrapper<T> BOOST_REF_CONST ref(T & t)
                                                               ^
In file included from ghost.h:26:0,
                 from bnet.cpp:23:
bnet.cpp:921:60: error: invalid initialization of non-const reference of type `C
BNET*&' from an rvalue of type `CBNET*'
      EXECUTE_HANDLER("BNetIPBanned", false, boost::ref(this))
                                                            ^
includes.h:88:53: note: in definition of macro `EXECUTE_HANDLER'
      bool Val = boost::python::extract<bool>( (*i)( __VA_ARGS__ ) );        \
                                                     ^
In file included from /usr/include/boost/thread/detail/thread.hpp:27:0,
                 from /usr/include/boost/thread/thread_only.hpp:22,
                 from /usr/include/boost/thread/thread.hpp:12,
                 from /usr/include/boost/thread.hpp:13,
                 from includes.h:44,
                 from ghost.h:26,
                 from bnet.cpp:23:
/usr/include/boost/ref.hpp:64:63: note: in passing argument 1 of `const boost::r
eference_wrapper<T> boost::ref(T&) [with T = CBNET*]'
 template<class T> inline reference_wrapper<T> BOOST_REF_CONST ref(T & t)
                                                               ^
In file included from ghost.h:26:0,
                 from bnet.cpp:23:
bnet.cpp:1070:62: error: invalid initialization of non-const reference of type `
CBNET*&' from an rvalue of type `CBNET*'
          EXECUTE_HANDLER("BNetTimeout", true, boost::ref(this))
                                                              ^
includes.h:88:53: note: in definition of macro `EXECUTE_HANDLER'
      bool Val = boost::python::extract<bool>( (*i)( __VA_ARGS__ ) );        \
                                                     ^
In file included from /usr/include/boost/thread/detail/thread.hpp:27:0,
                 from /usr/include/boost/thread/thread_only.hpp:22,
                 from /usr/include/boost/thread/thread.hpp:12,
                 from /usr/include/boost/thread.hpp:13,
                 from includes.h:44,
                 from ghost.h:26,
                 from bnet.cpp:23:
/usr/include/boost/ref.hpp:64:63: note: in passing argument 1 of `const boost::r
eference_wrapper<T> boost::ref(T&) [with T = CBNET*]'
 template<class T> inline reference_wrapper<T> BOOST_REF_CONST ref(T & t)
                                                               ^
In file included from ghost.h:26:0,
                 from bnet.cpp:23:
bnet.cpp:1072:59: error: invalid initialization of non-const reference of type `
CBNET*&' from an rvalue of type `CBNET*'
      EXECUTE_HANDLER("BNetTimeout", false, boost::ref(this))
                                                           ^
includes.h:88:53: note: in definition of macro `EXECUTE_HANDLER'
      bool Val = boost::python::extract<bool>( (*i)( __VA_ARGS__ ) );        \
                                                     ^
In file included from /usr/include/boost/thread/detail/thread.hpp:27:0,
                 from /usr/include/boost/thread/thread_only.hpp:22,
                 from /usr/include/boost/thread/thread.hpp:12,
                 from /usr/include/boost/thread.hpp:13,
                 from includes.h:44,
                 from ghost.h:26,
                 from bnet.cpp:23:
/usr/include/boost/ref.hpp:64:63: note: in passing argument 1 of `const boost::r
eference_wrapper<T> boost::ref(T&) [with T = CBNET*]'
 template<class T> inline reference_wrapper<T> BOOST_REF_CONST ref(T & t)
                                                               ^
In file included from ghost.h:26:0,
                 from bnet.cpp:23:
bnet.cpp: In member function `void CBNET::ProcessPackets()':
bnet.cpp:1372:62: error: invalid initialization of non-const reference of type `
CBNET*&' from an rvalue of type `CBNET*'
           EXECUTE_HANDLER("BNetLogged", true, boost::ref(this))
                                                              ^
includes.h:88:53: note: in definition of macro `EXECUTE_HANDLER'
      bool Val = boost::python::extract<bool>( (*i)( __VA_ARGS__ ) );        \
                                                     ^
In file included from /usr/include/boost/thread/detail/thread.hpp:27:0,
                 from /usr/include/boost/thread/thread_only.hpp:22,
                 from /usr/include/boost/thread/thread.hpp:12,
                 from /usr/include/boost/thread.hpp:13,
                 from includes.h:44,
                 from ghost.h:26,
                 from bnet.cpp:23:
/usr/include/boost/ref.hpp:64:63: note: in passing argument 1 of `const boost::r
eference_wrapper<T> boost::ref(T&) [with T = CBNET*]'
 template<class T> inline reference_wrapper<T> BOOST_REF_CONST ref(T & t)
                                                               ^
In file included from ghost.h:26:0,
                 from bnet.cpp:23:
bnet.cpp:1374:59: error: invalid initialization of non-const reference of type `
CBNET*&' from an rvalue of type `CBNET*'
       EXECUTE_HANDLER("BNetLogged", false, boost::ref(this))
                                                           ^
includes.h:88:53: note: in definition of macro `EXECUTE_HANDLER'
      bool Val = boost::python::extract<bool>( (*i)( __VA_ARGS__ ) );        \
                                                     ^
In file included from /usr/include/boost/thread/detail/thread.hpp:27:0,
                 from /usr/include/boost/thread/thread_only.hpp:22,
                 from /usr/include/boost/thread/thread.hpp:12,
                 from /usr/include/boost/thread.hpp:13,
                 from includes.h:44,
                 from ghost.h:26,
                 from bnet.cpp:23:
/usr/include/boost/ref.hpp:64:63: note: in passing argument 1 of `const boost::r
eference_wrapper<T> boost::ref(T&) [with T = CBNET*]'
 template<class T> inline reference_wrapper<T> BOOST_REF_CONST ref(T & t)
                                                               ^
In file included from ghost.h:26:0,
                 from bnet.cpp:23:
bnet.cpp: In member function `void CBNET::BotCommand(std::string, std::string, b
ool, bool)':
bnet.cpp:1604:61: error: invalid initialization of non-const reference of type `
CBNET*&' from an rvalue of type `CBNET*'
         EXECUTE_HANDLER("BNetCommand", true, boost::ref(this), User, Command, P
ayload)
                                                             ^
includes.h:88:53: note: in definition of macro `EXECUTE_HANDLER'
      bool Val = boost::python::extract<bool>( (*i)( __VA_ARGS__ ) );        \
                                                     ^
In file included from /usr/include/boost/thread/detail/thread.hpp:27:0,
                 from /usr/include/boost/thread/thread_only.hpp:22,
                 from /usr/include/boost/thread/thread.hpp:12,
                 from /usr/include/boost/thread.hpp:13,
                 from includes.h:44,
                 from ghost.h:26,
                 from bnet.cpp:23:
/usr/include/boost/ref.hpp:64:63: note: in passing argument 1 of `const boost::r
                                                               ^
In file included from ghost.h:26:0,
                 from bnet.cpp:23:
bnet.cpp:1606:58: error: invalid initialization of non-const reference of type `
CBNET*&' from an rvalue of type `CBNET*'
     EXECUTE_HANDLER("BNetCommand", false, boost::ref(this), User, Command, Payl
oad)
                                                          ^
includes.h:88:53: note: in definition of macro `EXECUTE_HANDLER'
      bool Val = boost::python::extract<bool>( (*i)( __VA_ARGS__ ) );        \
                                                     ^
In file included from /usr/include/boost/thread/detail/thread.hpp:27:0,
                 from /usr/include/boost/thread/thread_only.hpp:22,
                 from /usr/include/boost/thread/thread.hpp:12,
                 from /usr/include/boost/thread.hpp:13,
                 from includes.h:44,
                 from ghost.h:26,
                 from bnet.cpp:23:
/usr/include/boost/ref.hpp:64:63: note: in passing argument 1 of `const boost::r
eference_wrapper<T> boost::ref(T&) [with T = CBNET*]'
 template<class T> inline reference_wrapper<T> BOOST_REF_CONST ref(T & t)
                                                               ^
Makefile:45: recipe for target 'bnet.o' failed
make: *** [bnet.o] Error 1

**Comment by Grief-Code** [comment]
It seems you are missing the installation of boost python libs

**Comment by Grief-Code** [comment]
Can be closed due the fact that the plugin system was removed.
