### ISSUE TITLE
Unknown column

### ISSUE THREAD

**Issue by interkill** [OHSystem/OHSystem#428]
[Sun Jul 12 07:49:00 2015] [BNET] Unknown [xxx] sent command [p] with payload []
[Sun Jul 12 07:49:00 2015] [QUEUED: Eurobattle] [xxx]  Current Points: 0
[Sun Jul 12 07:49:00 2015] [MYSQL] error --- Unknown column 'month' in 'where clause'

I get this error

**Comment by Grief-Code** [comment]
Did you install our latest mysql scheme?

**Comment by interkill** [comment]
I use it ohsystem-remove_ohconnect_depency

mysql version = 5.6.17

**Comment by Grief-Code** [comment]
https://github.com/OHSystem/OHSystem/blob/master/openstats/install/sql_data.sql

This is the correct scheme for mysql on the current bot version.
Dont use an outdated branch, you can freely use the latest OHSystem build on master branch due the fact that you can fully disable OHConnect connections.
