### ISSUE TITLE
!pw - binding to the ip

### ISSUE THREAD

**Issue by Artyom91** [OHSystem/OHSystem#429]
@Grief-Code  It is difficult to make, what the team did not have to enter it again unless you change the IP address?

Or you can make a button to disable this feature for those who do not need it?

**Comment by Grief-Code** [comment]
They can simply remove the PW?
Just use
!PW PROTECTPW 0

**Comment by Artyom91** [comment]
Good.

**Comment by Artyom91** [comment]
@Grief-Code One problem. This command can be entered before the password is not correct.

**Comment by Grief-Code** [comment]
but that command requires the password itself :smile:

**Comment by Artyom91** [comment]
@Grief-Code No, I disabled without entering a password.

Version: https://github.com/OHSystem/OHSystem/tree/v1.01/ghost_v1

**Comment by Grief-Code** [comment]
I dont provide support for outdated version. Switch your ghost to the latest.
