### ISSUE TITLE
Games and Lives

### ISSUE THREAD

**Issue by interkill** [OHSystem/OHSystem#430]
![adsiz](https://cloud.githubusercontent.com/assets/4555310/8802862/92870abc-2fcc-11e5-9f19-a024bf04bf4b.png)

![adsi1](https://cloud.githubusercontent.com/assets/4555310/8802813/5d353974-2fcc-11e5-98d3-614084b9c503.png)

Lobby !unhost command ?

**Comment by Grief-Code** [comment]
?

**Comment by interkill** [comment]
Warcraft 3 Lobby me  !unhost commands using game closed but gamelist and lives no drop fix?

**Comment by Grief-Code** [comment]
unhost does not remove the lobby since the bot is not focused on userinput related commands, its only for autohosting.
