### ISSUE TITLE
Disables bot

### ISSUE THREAD

**Issue by Artyom91** [OHSystem/OHSystem#435]
Bot disabled on this line:

[GCBI] Garena user detected; userid=171170590, roomid=196716, RoomName=Russia DotA Room 018 (1.26a), experience=23, country=RU

What could be the problem?

**Comment by Grief-Code** [comment]
The problem is garena :hear_no_evil: 
Biggest bullshit platform on the net for gamers.

**Comment by Artyom91** [comment]
@Grief-Code 
Why falls ghost++ but not gcb?

**Comment by Grief-Code** [comment]
I dont know, you ned to debug and solve that for yourself. Im unable to test that or whatever.

**Comment by Artyom91** [comment]
@Grief-Code 

[MYSQL] error --- Lost connection to MySQL server during query
[GCBI] Garena user detected; userid=171170590, roomid=196614, RoomName=Russia DotA Room 012 (1.26a), experience=23, country=RU

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff5f132e4 in std::string::assign(std::string const&) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
(gdb) backtrace
#0  0x00007ffff5f132e4 in std::string::assign(std::string const&) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x00000000004e7940 in operator= (__str=..., this=0x7fffffffbce0) at /usr/include/c++/4.9/bits/basic_string.h:555
#2  CBaseGame::EventPlayerJoined (this=0x2429a00, potential=0x11d2630, joinPlayer=0x2442fe0) at game_base.cpp:2617
#3  0x00000000004ff370 in CPotentialPlayer::ProcessPackets (this=0x7fffffffbce0) at gameplayer.cpp:195
#4  0x00000000004fd570 in CPotentialPlayer::Update (this=0x11d2630, fd=<optimized out>) at gameplayer.cpp:117
#5  0x00000000004d7af0 in CBaseGame::Update (this=this@entry=0x2429a00, fd=fd@entry=0x7fffffffe840, send_fd=send_fd@entry=0x7fffffffe8c0) at game_base.cpp:748
#6  0x0000000000468f63 in CGame::Update (this=0x2429a00, fd=0x7fffffffe840, send_fd=0x7fffffffe8c0) at game.cpp:966
#7  0x00000000005199fd in CGHost::Update (this=0x86e6d0, usecBlock=1000, usecBlock@entry=50000) at ghost.cpp:866
#8  0x000000000040bea1 in main (argc=<optimized out>, argv=<optimized out>) at ghost.cpp:329
