### ISSUE TITLE
with observer hcl is not set

### ISSUE THREAD

**Issue by cipriant** [OHSystem/OHSystem#439]
pls fix this bug: if i join observer and I have the bot observer ( 2 obserevrs) hcl is not set.
 tested with DotA v6.83d.w3x and hcl 'sd', 1 player + me observer + default observer (fake)

**Comment by Grief-Code** [comment]
Uhm thats because the HCL is only working on players i think.
Im not fully sure, but i think it was like 1 HCL Char / player. The reason why observers arent working is due the fact that there is only 1 player. An observer does not count into that, thats a map issue and not a bot related issue.

**Comment by cipriant** [comment]
but is latest official dota map. in my opinon is a hcl issue, the initial bot code wasn't tested for 2 observers.
so, test 1, with hcl 'sd':
1 me blue slot
1 fake observer
result: hcl succes applied.

so, test 2, with hcl 'sd':
1 player on blue slot
1 fake observer
me 2'nd observer.
 (so 2 observers)
result: hcl succes fail.

**Comment by Grief-Code** [comment]
As said, i do not think thats a result of the bot. In order to test that, add a computer to slot 12 and try again (or if you have multiply fakeplayer patch, add another fakeplayer to slot 12)

**Comment by cipriant** [comment]
Hcl failed with 2 fake observers.
1 player was for testing...

**Comment by cipriant** [comment]
BTW.  In test 1 hcl was successful,  with 1 player

**Comment by cipriant** [comment]
Hcl failed with 2 fake observers.
1 player was for testing...
